//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XingWinFormApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR1422
    {
        public string regdate { get; set; }
        public string hname { get; set; }
        public string shcode { get; set; }
        public int price { get; set; }
        public string sign { get; set; }
        public int change { get; set; }
        public double diff { get; set; }
        public int volume { get; set; }
        public double diff_vol { get; set; }
        public int offerrem1 { get; set; }
        public int bidrem1 { get; set; }
        public string last { get; set; }
        public int lmtdaycnt { get; set; }
    }
}
